In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import torch
from torch import nn

/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


* Binary cross entropy and log loss are same thing
* The formula for log-loss & binary cross entropy are same.

In [2]:
g_truths = np.random.randint(0, 2, size=(20)).astype(np.float32)
preds = np.random.random(size=(20))

In [3]:
bce = tf.losses.BinaryCrossentropy()

In [4]:
bce(g_truths, preds).numpy()

0.7056488336261532

In [5]:
np.sum(-(g_truths * np.log(preds) + (1 - g_truths) * np.log((1 - preds)))) / len(preds)

0.705649074830514

In [6]:
# For torch you need to convert to torch tensor first
p_1 = torch.Tensor(preds)
g_1 = torch.Tensor(g_truths)

In [7]:
torch_loss = nn.BCELoss()
torch_loss(p_1, g_1)

tensor(0.7056)

In [10]:
bce(np.array([1]), np.array([0.9]))

<tf.Tensor: shape=(), dtype=float64, numpy=0.1053604045467214>

In [11]:
bce(np.array([1]), np.array([0.99]))

<tf.Tensor: shape=(), dtype=float64, numpy=0.010050234843405595>

In [12]:
bce(np.array([1]), np.array([0.8]))

<tf.Tensor: shape=(), dtype=float64, numpy=0.22314342631421757>

In [13]:
bce(np.array([1]), np.array([0.3]))

<tf.Tensor: shape=(), dtype=float64, numpy=1.2039724709926583>

In [14]:
bce(np.array([1]), np.array([0.1]))

<tf.Tensor: shape=(), dtype=float64, numpy=2.302584092994546>

* So in general we can say that as the predicted value is farther more and more from actual value meaning log-loss value is higher. So, in cases where you want to reduce the distance between predicted and ground truth this loss function is ideal choice.
* One very important aspect here is as value goes more in other side the loss value becomes very high.